### ISSUE TITLE
Contributing and testing

### ISSUE THREAD

**Issue by xe2io** [immich-app/immich-charts#1]
Hi Everyone,

I recently got a helm chart working based on the (now deprecated) [k8s-at-home](https://github.com/k8s-at-home/charts) project and would be happy to contribute if there's a need for a starting point.
  
It's a bit bare-bones and is enough to get Immich deployed to a single node (everything (minus proxy) deployed into a single pod) and uses the Bitnami redis and postgresql charts.
  
I'd also be happy to help test- I'm deploying on k3s (single node for now) with a Traefik v2 ingress.

Thanks in advance!

**Comment by PixelJonas** [comment]
Hey @xe2io srry for not seeing your message. Could you try testing the current draft PR https://github.com/immich-app/immich-charts/pull/2 

It's also based on bjw-s common library. I'd like your feedback on how I adapted it

**Comment by PixelJonas** [comment]
@xe2io we merged https://github.com/immich-app/immich-charts/pull/2 and have the first iteration of a chart in `main` feel free to contribute. There's still a lot to do (like CI, releasing the chart to a github-page, adding artifacthub annotations, etc.) PR's are very welcome
