### ISSUE TITLE
Initial DB creation fails

### ISSUE THREAD

**Issue by mzehrer** [immich-app/immich-charts#100]
If I activate the Postgres in the chart, the pod fails with the following output:

```
chmod: changing permissions of '/bitnami/postgresql/data': Operation not permitted
popen failure: Cannot allocate memory
initdb: error: The program "postgres" is needed by initdb but was not found in the
same directory as "/usr/lib/postgresql/14/bin/initdb".
Check your installation.

```

**Comment by bo0tzz** [comment]
> popen failure: Cannot allocate memory

This sounds like you're out of memory

**Comment by mzehrer** [comment]
No, I don't think this is a memory issue, there is enough memory. I now switched to a separate database based on CloudNative-PG (https://docs.pgvecto.rs/admin/kubernetes.html) and this works.
