### ISSUE TITLE
Ability to add external libraries as a PVC - PR ready

### ISSUE THREAD

**Issue by sapstar** [immich-app/immich-charts#109]
Hi,

I made a change to add ability for external libraries to be mounted as a pvc. Never submitted any PR's to open projects. Unsure how to do it.
Locally I did the changes in a branch, but when pushing it looks like I don't have access to do it.
`fatal: unable to access 'https://github.com/immich-app/immich-charts.git/': The requested URL returned error: 403`

Can you please let me know how I can submit a PR.

Thanks

**Comment by sapstar** [comment]
I think I figured it out now. I submitted a PR with the changes.

**Comment by bo0tzz** [comment]
See #70
