### ISSUE TITLE
Changes on machine-learning break the deployment

### ISSUE THREAD

**Issue by alexbarcelo** [immich-app/immich-charts#11]
I recently updated to v1.49.0 image version and everything seems to keep working EXCEPT the machine-learning image.

Looking a git into the main repo, it sems as if the Dockerfile for machine-learning image has been changed to have the CMD within the image metadata.

I believe that there is no need to add `args` and the shell in the deployment. I hot-patched that (removed those lines from the deployment manifest) and now the deployment seems to start.

I suppose that a new chart release, with a more up-to-date immich version, and changing this machine learning would work. But I always break things when I try to modify charts, sorry for not proposing the PR myself.

**Comment by bo0tzz** [comment]
We already have a PR open to fix this: #10. Just need to get it released.

**Comment by alexbarcelo** [comment]
I apologize. I searched only through Issues, not Pull requests. I just realized my mistake.

Sorry for the noise. Glad to hear that!
