### ISSUE TITLE
Latest release (v1.113.1) breaks immich machine learning default URL configuration

### ISSUE THREAD

**Issue by mike12806** [immich-app/immich-charts#119]
If I use the helm chart but swap to the latest Immich version (v1.113.1), I get this error on startup in the maching learning pod / container:

```
2024-09-03T17:33:21.328319798-04:00 [09/03/24 17:33:21] ERROR    connection to ('::', 3003) failed: [Errno 97]      
                             Address family not supported by protocol 
```

I'm guessing this section of the values.yaml file needs to be modified under the env variables section, maybe? 

`  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
`

Chart version is 0.7.2

**Comment by bo0tzz** [comment]
I don't think this has anything to do with the ml url env var. Can you post the full logs & values.yaml, and some detail about your environment/network?

**Comment by mike12806** [comment]
##Thanks @bo0tzz. I realized the issue was due to ipv6 being enabled on the underlying host. Specifying an ipv4 address specifically solved the issue for me
