### ISSUE TITLE
Helm chart installation fails as dependency chart `common` is no longer available

### ISSUE THREAD

**Issue by shikharbhardwaj** [immich-app/immich-charts#120]
Helm chart installation fails because the helm repo of the dependency chart `common` in repo https://bjw-s.github.io/helm-charts is no longer available.

```
helm repo add bjw-s https://bjw-s.github.io/helm-charts
Error: looks like "https://bjw-s.github.io/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://bjw-s.github.io/helm-charts/index.yaml : 404 Not Found
```

Looks like it has moved from https://bjw-s.github.io/helm-charts to https://bernd-schorgers.github.io/helm-charts because of a GH username change.

**Comment by bo0tzz** [comment]
This is due to https://github.com/bernd-schorgers/helm-charts/issues/355. Should resolve itself once the username shuffle is done, but I'll leave this open for now.

**Comment by shikharbhardwaj** [comment]
Looks like the problem has been fixed for now after a rename back to the original, will close this.
