### ISSUE TITLE
 immich-postgresql statefulset resource limits are insufficient. 

### ISSUE THREAD

**Issue by LelandSindt** [immich-app/immich-charts#127]
I recently upgraded from 0.7.0 to 0.8.0 of the helm chart and noticed the following changes for the  immich-postgresql statefulset resource limits 

```
           resources:
-            limits: {}
+            limits:
+              cpu: 150m
+              ephemeral-storage: 2Gi
+              memory: 192Mi
```

With these limits in place I found immich to slow/almost un-usable.  For now I have removed the limit in my deployment. I will follow up here as I work to find more reasonable defaults.

**Comment by LelandSindt** [comment]
... after thinking about this for a bit today.. I am just going to remove these limits from my deployment/implementation.

**Comment by addich** [comment]
i noticed the same issue, found the immich works slow.

with old chart it was:
```
          resources:
            limits: {}
            requests:
              cpu: 250m
              memory: 256Mi
```

with new chart the deployment gets:
```
    Limits:
      cpu:                150m
      ephemeral-storage:  2Gi
      memory:             192Mi
    Requests:
      cpu:                100m
      ephemeral-storage:  50Mi
      memory:             128Mi
```

not sure what would be a good setting, but for now i overwrite the new default with the old via the values file:
```
postgresql:
  enabled: true
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.2.0
  global:
    postgresql:
      auth:
        username: DELETED
        database: DELETED
        password: DELETED
  primary:
    resources:
      limits: {}
      requests:
        cpu: 250m
        memory: 256Mi
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;
```

**Comment by rholloway** [comment]
Thanks @addich and @LelandSindt. For me postrges is actually crashing regularly due to OOM with the current settings, particularly when I'm doing imports or other tasks. The code above helped me change quickly (I still find this helper chart confusing)
