### ISSUE TITLE
improvement: implement to github actions

### ISSUE THREAD

**Issue by orbatschow** [immich-app/immich-charts#13]
It would be great to incorporate something like https://github.com/helm/chart-releaser-action into the release workflow. 

This would reduce the number of errors and could be used to fully automate a new release in conjunction with: https://github.com/immich-app/immich-charts/issues/12

**Comment by bo0tzz** [comment]
@PixelJonas would you be able to take a look at this?

**Comment by PixelJonas** [comment]
It is on my todo, but I'm happy to  give someone else a shot on this
