### ISSUE TITLE
Clarification about the template layout

### ISSUE THREAD

**Issue by bniedermayr** [immich-app/immich-charts#134]
Hi guys,

I'm currently trying to understand how you make use of the common helm charts library. And I'm bit confused about how you make use of the common helm charts library. As an example we could focus on the [server.yaml](https://github.com/immich-app/immich-charts/blob/main/charts/immich/templates/server.yaml) file.

Taking a look into the [common helm charts library example](https://bjw-s.github.io/helm-charts/docs/app-template/) I would assume to find somewhat similar like this:

```yaml
controllers:
  server: 
 .....
```

Also the `{{- define "immich.server.hardcodedValues" -}}` and the 
```yaml
{{ if .Values.server.enabled }}
{{- $ctx := deepCopy . -}}
{{- $_ := get .Values "server" | mergeOverwrite $ctx.Values -}}
{{- $_ = include "immich.server.hardcodedValues" . | fromYaml | merge $ctx.Values -}}
{{- include "bjw-s.common.loader.all" $ctx }}
{{ end }}
```
feel more like magic than the documented process.
Maybe you can clarify me about the reason behind the decision to deviate from the documentation....

**Comment by bo0tzz** [comment]
The docs you're looking at are for app-template. That chart uses common-library, as does this Immich one. The arcane invocation in our templates is to call into the common-library chart once for each Immich component without having things interfere.

Also note that Immich is using an older version of the library than you're looking at.

**Comment by bniedermayr** [comment]
Thanks or the disenchantment and clarification! 
I wasn't aware that `common-library` and the `app-template` are different things... have to study further here.

**Comment by bniedermayr** [comment]
@bo0tzz So a PR updating to the latest version wouldn't hurt i guess?

**Comment by bo0tzz** [comment]
It would, but only because it'd be a breaking change and I've been saving those up (see #92) until I have a better way to communicate changelogs. I'm leaning towards doing that sometime soon though.

**Comment by bniedermayr** [comment]
> (see https://github.com/immich-app/immich-charts/issues/92)
Ah, so there is already some collaboration going on.
