### ISSUE TITLE
List chart on artifacthub

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich-charts#14]
See https://artifacthub.io/docs/topics/repositories/helm-charts/

Probably depends on #12.

**Comment by bo0tzz** [comment]
I've registered the chart on artifacthub and it's currently indexing. I would like to also set up [verified publisher](https://artifacthub.io/docs/topics/repositories/#verified-publisher), which needs an extra file to be served on the chart repository URL. Can we just add that to the gh-pages branch manually, or does it need to be processed by the chart-releaser workflow? @orbatschow / @PixelJonas

**Comment by orbatschow** [comment]
@bo0tzz the chart releaser should only touch the `index.yaml` file within the `gh_pages` branch. IMHO there is nothing that would preventing the additional file by opening a PR.

**Comment by PixelJonas** [comment]
simply adding it as file to the `gh-pages` branch should be enough and not interfere with the releaser
