### ISSUE TITLE
Unable to start Immich server on fresh install

### ISSUE THREAD

**Issue by JeffResc** [immich-app/immich-charts#142]
I'm unable to get Immich Server running on a fresh install and no helpful log output is being set, even with `IMMICH_LOG_LEVEL` set to `verbose`. Prior to attempting to start Immich, I have deleted everything in the namespace including all PVCs.

I also have a custom `securityContext` defined, but I have attempted without it, yielding the same result.

<details>
<summary>values.yaml</summary>
<br>
<pre>
image:
  tag: v1.119.1
immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich-library
  configuration: {}
postgresql:
  enabled: true
  global:
    storageClass: msi-cubi
redis:
  enabled: true
  global:
    storageClass: msi-cubi
server:
  enabled: true
  podSecurityContext:
    fsGroup: 10099
  securityContext:
    runAsUser: 10099
    runAsGroup: 10099
machine-learning:
  enabled: true
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: pvc
      accessMode: ReadWriteMany
      storageClass: msi-cubi
</pre>
</details>

<details>
<summary>Describe immich-server pod</summary>
<br>
<pre>
Name:             immich-server-55bff57558-whd24
Namespace:        immich
Priority:         0
Service Account:  default
Node:             k3s-n02/192.168.0.202
Start Time:       Wed, 30 Oct 2024 13:26:47 -0400
Labels:           app.kubernetes.io/instance=immich
                  app.kubernetes.io/name=server
                  pod-template-hash=55bff57558
Annotations:      <none>
Status:           Running
IP:               10.0.1.185
IPs:
  IP:           10.0.1.185
Controlled By:  ReplicaSet/immich-server-55bff57558
Containers:
  immich-server:
    Container ID:   containerd://eaef83ac7ee0488d3b50f820fb4d6541737cf6765f3f4f228fe6fa0cdad512e8
    Image:          ghcr.io/immich-app/immich-server:v1.119.1
    Image ID:       ghcr.io/immich-app/immich-server@sha256:d63feeee7a41095b3c1b18607d86a1264bcac53728a19f538a77a6e66043f492
    Ports:          2283/TCP, 8081/TCP, 8082/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 30 Oct 2024 13:26:50 -0400
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:http/api/server/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:http/api/server/ping delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:        http-get http://:http/api/server/ping delay=0s timeout=1s period=10s #success=1 #failure=30
    Environment:
      DB_DATABASE_NAME:             immich
      DB_HOSTNAME:                  immich-postgresql
      DB_PASSWORD:                 [REDACTED]
      DB_USERNAME:                  immich
      IMMICH_MACHINE_LEARNING_URL:  http://immich-machine-learning:3003
      IMMICH_TELEMETRY_INCLUDE:     all
      REDIS_HOSTNAME:               immich-redis-master
    Mounts:
      /usr/src/app/upload from library (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-k6pc6 (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True
  Initialized                 True
  Ready                       False
  ContainersReady             False
  PodScheduled                True
Volumes:
  library:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  immich-library
    ReadOnly:   false
  kube-api-access-k6pc6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  4m42s                 default-scheduler  Successfully assigned immich/immich-server-55bff57558-whd24 to k3s-n02
  Normal   Pulled     4m40s                 kubelet            Container image "ghcr.io/immich-app/immich-server:v1.119.1" already present on machine
  Normal   Created    4m40s                 kubelet            Created container immich-server
  Normal   Started    4m40s                 kubelet            Started container immich-server
  Warning  Unhealthy  61s (x22 over 4m30s)  kubelet            Startup probe failed: Get "http://10.0.1.185:2283/api/server/ping": dial tcp 10.0.1.185:2283: connect: connection refused
</pre>
</details>

<details>
<summary>Logs for immich-server pod</summary>
<br>
<pre>
Initializing Immich v1.119.1
Detected CPU Cores: 4
Starting api worker
Starting microservices worker
[Nest] 17  - 10/30/2024, 5:32:02 PM     LOG [Api:EventRepository] Initialized websocket server
[Nest] 7  - 10/30/2024, 5:32:03 PM     LOG [Microservices:EventRepository] Initialized websocket server
[Nest] 17  - 10/30/2024, 5:32:03 PM     LOG [Api:MapRepository] Initializing metadata repository
</pre>
</details>

**Comment by bo0tzz** [comment]
See https://github.com/immich-app/immich-charts/issues/130#issuecomment-2410351150, this is caused by some weird default resource limits from the upstream bitnami chart.
