### ISSUE TITLE
immich-server frontend not loading after upgrading replicaset instances amount

### ISSUE THREAD

**Issue by bounteous17** [immich-app/immich-charts#143]
After incrementing `immich-server` k8s _replicaset_ from 1 to 2, causes app frontend not loading.
Anyway the API is still working after this change because the smartphone app is still working.
On the other hand, the error that appears on the frontend is the following (the app works perfectly with a single POD):

![image](https://github.com/user-attachments/assets/bd2a94a1-a653-4dd5-848e-4772e49d32ff)
```
start.kTbs4qOW.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
entry.Dp1aKnev.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
photos:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://immich.home-lab.<example>.ovh/_app/immutable/entry/start.kTbs4qOW.js
Promise.then
(anonymous) @ photos:179
photos:1 The resource https://immich.home-lab.<example>.ovh/_app/immutable/assets/OverpassMono.XkUhFDDw.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
photos:1 The resource https://immich.home-lab.<example>.ovh/_app/immutable/assets/Overpass.DCP28BvT.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

The _deployment_ doesn't show any error and the _pvc_ `immich-data` using `longhorn` _classtorage_ is attached successfully for both instances. I mention this because it seems that the app cannot serve the build id that should be available from the _pvc_

![image](https://github.com/user-attachments/assets/16e3ce02-e287-444d-a378-f70e775a7c10)

Extra info:
- app version: `v1.119.1`
- chart version: `0.8.4`

**Comment by bo0tzz** [comment]
Try clearing your browser cache

**Comment by bounteous17** [comment]
> Try clearing your browser cache

Updating the `immich-server` app version to `1.120.1` fixed the issue
