### ISSUE TITLE
Remove postgres container limits

### ISSUE THREAD

**Issue by ViktorBarzin** [immich-app/immich-charts#145]
Currently the postgres container in the helm chart has limits. This creates problems for bigger deployments where more data is stored - it is painfully slow and oftentimes connections timeout or the server/immich crash altogether.

Proposal - remove or make the postgres limits configurable via values. Perhaps no limits would be sensible defaults as debugging this was really quite difficult.

**Comment by bo0tzz** [comment]
A valid request, but I'm planning on #129 instead. The postgres here is a dependency through a bitnami chart, they're the ones that set these limits, and they are already configurable through the values.
