### ISSUE TITLE
Add support for Typesense deployment

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich-charts#18]
Immich release [v1.51.0](https://github.com/immich-app/immich/releases/tag/v1.51.0) added an extra Typesense container to the stack that is currently required. This is another infrastructure component like postgres and redis.

While there is a typesense helm chart at https://github.com/Spittal/typesense-helm, it hasn't been updated for a while. Typesense doesn't need anything specific and so it would also be totally fine to use the common-library to deploy it.

**Comment by Tarik02** [comment]
Actually it is not required. As a temporary workaround you can disabled it by adding:
```
common_env:
  ...
  TYPESENSE_ENABLED: false # this
```

**Comment by PixelJonas** [comment]
This should be resolved with #20
