### ISSUE TITLE
use http probes

### ISSUE THREAD

**Issue by uhthomas** [immich-app/immich-charts#21]
HTTP probes should be more reliable and can convey more information than TCP probes. I would suggest that if HTTP is available then it should be used. TCP probes are really only useful for protocols which use TCP but not HTTP.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#http-probes

**Comment by bo0tzz** [comment]
Will be fixed by #20

**Comment by PixelJonas** [comment]
This should be resolved with #20 now
