### ISSUE TITLE
Immich proxy not starting on latest version

### ISSUE THREAD

**Issue by Y0ngg4n** [immich-app/immich-charts#32]
```
k logs -n storage immich-proxy-659f8bb687-ccb7z
exec /docker-entrypoint.sh: exec format error
```

**Comment by bo0tzz** [comment]
Nothing has changed about the proxy recently. What CPU architecture are you running on?

**Comment by Y0ngg4n** [comment]
@bo0tzz standard AMD Ryzen 5 5600G with Radeon Graphics (1) so x64

**Comment by bo0tzz** [comment]
@Y0ngg4n are you still having this issue?

**Comment by Y0ngg4n** [comment]
@bo0tzz nop
