### ISSUE TITLE
Deploy without ML component

### ISSUE THREAD

**Issue by irreleph4nt** [immich-app/immich-charts#40]
Hi,

I am currently looking into replacing nextcloud with immich as the former won't fix the broken auto-upload for iOS devices. From what I have read so far, the ML component in this chart is pretty high on resource consumption, which is a problem because I run on a single node cluster.
 
Can immich be deployed and function witholut the ML component?
If so, is setting "enabled: false" in the values.yaml file sufficient to achieve this goal?
What features etc. will I be missing out on when ML is not available to immich?

Thanks, this looks like a great app!

**Comment by bo0tzz** [comment]
Yes, most of this should be documented at https://immich.app/docs/FAQ#why-is-immich-slow-on-low-memory-systems-like-the-raspberry-pi. You can use the settings documented there to disable ML, and to disable the deployment in the chart you can set:
```yaml
machine-learning:
  enabled: false
```
