### ISSUE TITLE
compatibility with immich 1.88

### ISSUE THREAD

**Issue by mvivaldi** [immich-app/immich-charts#49]
Hello,

I successfully upgraded to immich version 1.87 using this chart without encountering any issues. However, I've noticed a warning in the main immich interface regarding certain disruptive changes in version 1.88. You can find more details about these changes here: https://github.com/immich-app/immich/discussions/5086

Is there a plan to update the chart to align with these changes?

Thank you!

**Comment by dcshoes23** [comment]
There is an open PR [here](https://github.com/immich-app/immich-charts/pull/50)
