### ISSUE TITLE
Ingress now points to machine learning service

### ISSUE THREAD

**Issue by djjudas21** [immich-app/immich-charts#51]
I've just upgraded to Immich v1.88.1 using Helm chart version v0.2.0.

It looks like somehow in the removal of the web and proxy deployments, the default Ingress has ended up pointing to the `immich-machine-learning service`. I assume it should be pointing at the `immich-server` service? In fact it looks like the original ingress has been removed and replaced with a new one with a different name.

```
[jonathan@poseidon immich]$ kubectl get ingress
NAME                      CLASS    HOSTS               ADDRESS     PORTS     AGE
immich-machine-learning   public   immich.gazeley.uk   127.0.0.1   80, 443   11m
```

```
[jonathan@poseidon immich]$ kubectl describe ingress immich-machine-learning
Name:             immich-machine-learning
Labels:           app.kubernetes.io/instance=immich
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=machine-learning
                  app.kubernetes.io/version=v1.88.0
                  helm.sh/chart=immich-0.2.0
Namespace:        immich
Address:          127.0.0.1
Ingress Class:    public
Default backend:  <default>
TLS:
  ingress-tls terminates immich.mydomain.uk
Rules:
  Host               Path  Backends
  ----               ----  --------
  immich.mydomain.uk  
                     /   immich-machine-learning:3003 (10.1.106.39:3003)
Annotations:         cert-manager.io/cluster-issuer: letsencrypt-prod
                     meta.helm.sh/release-name: immich
                     meta.helm.sh/release-namespace: immich
                     nginx.ingress.kubernetes.io/proxy-body-size: 0
Events:              <none>
```

**Comment by bo0tzz** [comment]
The ingress in the default values file is definitely pointing correctly to `server`. Have you updated your values to match? Can you post your full values.yaml?

**Comment by djjudas21** [comment]
Sorry, you're right, it was a yaml formatting error. I took out the `web` and `proxy` settings and incorrectly thought that `ingress` was a top level key (it is on most other charts derived from `bjw-s/common`) but of course it was indented under `web` and now it became indented under `machine-learning`. I've fixed it now.
