### ISSUE TITLE
Request to support service type LoadBalancer

### ISSUE THREAD

**Issue by madimadi** [immich-app/immich-charts#54]
Hi,

In case I'm not mistaken, there is a "wired-in" ClusterIP in helm templates for services. 
Can you add service type as a value in templates, to be able to set from values?

Thanks

**Comment by bo0tzz** [comment]
This chart builds on the [common-library](https://github.com/bjw-s/helm-charts/blob/923ef40a39520979c98f354ea23963ee54f54433/charts/library/common), so you can use all of the values that are available there. In this case something like
```yaml
server:
  service:
    main: 
      type: LoadBalancer
```
(See https://github.com/bjw-s/helm-charts/blob/923ef40a39520979c98f354ea23963ee54f54433/charts/library/common/values.yaml#L286 for all the options)
