### ISSUE TITLE
Implement renovate to update minor tag to immich helm chart

### ISSUE THREAD

**Issue by yodatak** [immich-app/immich-charts#57]
Hi thanks for this official chart it  could cool to implement renovate to permit to auto upgrade the minor tagg version of the helm chart

**Comment by bo0tzz** [comment]
Doing this would mean a lot of unnecessary releases for the chart. I try to only do a release when the chart itself has changes, which is usually when there are (breaking) changes in how Immich needs to be deployed.

For day-to-day updates of the Immich version, you can override the tag used from the values.yaml, like such: https://github.com/bo0tzz/kube/blob/main/apps/immich/immich.yaml#L57
