### ISSUE TITLE
New Version of immich need pgvector-v0.2.0 

### ISSUE THREAD

**Issue by yodatak** [immich-app/immich-charts#66]
Hi this chart need some updating with the breaking changes

**Comment by samholton** [comment]
I was wondering what the plan was for the chart. It seems like the tag is not bumped with each version. I've been providing the tag and now postgres tag for each deploy. If the goal is to release the chart with each release of immich itself, I'm happy to lend a hand.

**Comment by djjudas21** [comment]
@samholton I already raised the issue of tag bumping in #46 but my PR was closed and I was told that they do not plan to bump the chart at each release of Immich and instead the user is supposed to override the tag in the Helm values. In my view, this is wrong - or at the very least, anomalous behaviour when compared to how the vast majority of Helm charts are maintained. It means any new user of Immich who installs via Helm chart using default values will get an old version of Immich, and are liable to run into (and report) bugs that have already been fixed.

It seems there are at least a few people who also agree with us, so maybe it's worth opening a new issue to kick off a discussion.

**Comment by yodatak** [comment]
> @samholton I already raised the issue of tag bumping in #46 but my PR was closed and I was told that they do not plan to bump the chart at each release of Immich and instead the user is supposed to override the tag in the Helm values. In my view, this is wrong - or at the very least, anomalous behaviour when compared to how the vast majority of Helm charts are maintained. It means any new user of Immich who installs via Helm chart using default values will get an old version of Immich, and are liable to run into (and report) bugs that have already been fixed.
> 
> It seems there are at least a few people who also agree with us, so maybe it's worth opening a new issue to kick off a discussion.

I'm agree to we should have a working chart with latest version ready to use out of the box

**Comment by samholton** [comment]
Yeah, it was unexpected behavior when I initially installed the chart. I ended up using an old version until I realized the chart did not track the app. I was new to the project and just spun it up to test it out.

If that is the decision, I think it should be documented in the readme or default values.

**Comment by samholton** [comment]
https://github.com/immich-app/immich-charts/pull/67
