### ISSUE TITLE
Current chart version is 2 releases behind Immich

### ISSUE THREAD

**Issue by michalramus** [immich-app/immich-charts#68]
Hi, could you update version of chart to match latest Immich release?

**Comment by bo0tzz** [comment]
Updating the chart every time there is a new Immich version is unnecessary. Updates are usually only done when necessary, for example when there is a breaking change. You can set the latest version in your own values.yaml
```yaml
image:
  tag: v1.97.0
```

**Comment by michalramus** [comment]
Please add information about this, because it is a little confusing for new Immich users(like me).

**Comment by bo0tzz** [comment]
#69

**Comment by michalramus** [comment]
Thank you:)

**Comment by maybeanerd** [comment]
> Updating the chart every time there is a new Immich version is unnecessary. 

How so? When using a chart, I generally expect it to keep versions up to date, especially abstracting away things like e.g. compatability with other systems (DB, redis, etc)

Currently, as this chart doesn't provide this for me, I maintain effectively a fork for my own use.

I think this repo could be set up to update versions mostly automatically, keeping manual effort low.
In my repo (https://github.com/maybeanerd/home-cluster/tree/main/charts%2Fimmich) I use renovate.
It can be configured to:
- autobump patch versions
- prepare PRs, but don't merge them for minor versions (as they might be breaking until immich hits stable. This is a bit of manual work, as one would need to review the patchnotes before merging)
- same for major version releases
- autobump the chart version according to the proposed change: minor immich version change -> minor chart version bump

Would you consider something like this?
If so, I could prepare a PR with the config for you to check out in more detail.

**Comment by bo0tzz** [comment]
> because with this, I have to check every update by my own if there are any breaking changes. 

You should be doing that anyways.

> why you are against automatic updates

This chart doesn't get (or need) many updates at the moment. Automatic app version bumps would result in a lot of effectively empty version churn. Alternatively, if the chart version was not bumped with every app version change, those wouldn't make it into a release for quite a while and so the situation wouldn't be that different from now.

**Comment by tzabbi** [comment]
> You should be doing that anyways.

I mean if the new immich version is still compatible with your helm chart.

> This chart doesn't get (or need) many updates at the moment. Automatic app version bumps would result in a lot of effectively empty version churn. Alternatively, if the chart version was not bumped with every app version change, those wouldn't make it into a release for quite a while and so the situation wouldn't be that different from now.

An update of the image version is not an empty version of the helm chart, it is a valid point to release a new version of the helm chart. You don't have to update the chart functionality to release a new version. 

In helm it is a bad practice to define the image tag by your own in a custom values.yaml

**Comment by tzabbi** [comment]
I would prefer to use the official helm chart, but under these circumstances it is probably best if you could make yours available public, so that not everyone has to create their own helm chart. 
It would be good if your fork remains upstream compatible with the official helm repo.

**Comment by maybeanerd** [comment]
I agree, an official chart would be best. TBH I didn't think of providing a softfork, rather a fully rebuilt version e.g. using the latest (v4) version of the common chart, etc. But now seeing you mention this, a soft fork is probably a better solution for the wider community where we "just" provide a version of this chart that can be used as is, with application updates in mind. It might bring improvements to upstream that way too, which would be nice.

**Comment by bo0tzz** [comment]
Better yet, use gitops (like you should anyways) and have Renovate update the `image.tag` in your values yaml.

**Comment by cellexec** [comment]
I’d like to reopen this issue.

I understand the concern that updating the Helm chart for every new tag release might seem like a lot of work. However, at the moment even manual updates don’t work properly.

When deploying the Helm chart with default values, the app runs correctly on version `v1.119.0`. But setting the tag manually to a higher version, such as the current `v1.140.0`, fails. I tested this on a fresh k3s cluster, and it didn’t work.

It seems there’s a breaking change that the Helm chart doesn’t account for. It would be really helpful to have the latest working tag reflected in the chart. At my company, we handle this through CI/CD pipelines, and with GitHub Actions this shouldn’t be too difficult. The challenge is that each release would still need to be tested before being made available for everyone.

Can we restart the discussion around this? I’d be happy to contribute and help with the effort.

Kind regards,
Cellexec

**Comment by 3uzbcqje** [comment]
The thumbs up and down counts on the comments in this issue indicate that the community would prefer to have the chart updated with the latest version of the app whenever it comes out. It is churn, but churn isn't necessarily bad. It shows that the project is active, and having more contributors gives more credibility to the project. Its also frustrating to install an app with a chart only to see a "New version available" immediately after getting it working. We can do better. Would you please reconsider my PR to update to the current version?

**Comment by JohnStarich** [comment]
Thank you @bo0tzz for your ongoing maintenance. ❤️ 

>As discussed upthread, this is unnecessary churn and I don't plan on tracking every Immich release at the moment.

Would you be open to the idea of automating tag-based releases to track the main repo's releases, thereby reducing manual churn? The idea is essentially a cron job that checks for new main releases, then automatically pushes new tags and publishes releases.

I've seen this pattern used quite effectively in other popular helm repos, and it should address the above maintenance concern while also significantly reducing friction (and increasing adoption).

>(ideally in the form of people getting consistently involved in maintaining this chart). That might make room to consider changes like this, but no promises.

Are you looking for maintainers? It sounds like a couple folks here would be interested in lending a hand if you're open to it.

**Comment by tzabbi** [comment]
@JohnStarich consider using this project is not an option? https://github.com/maybeanerd/immich-charts

**Comment by JohnStarich** [comment]
I appreciate the thought, but I'd like to work within the realm of the official chart if I can. I may give it a try later. 🙂

**Comment by bo0tzz** [comment]
I'm already running renovate here, automation isn't the issue. Help with maintaining the chart is always welcome, though I'm relatively happy with it right now so idk what there would really be left to do.

**Comment by JohnStarich** [comment]
Aha, ok. May I ask what you mean by churn? I thought it might be about pushing commits, where tags could help.
