### ISSUE TITLE
Arm(64) is not supported

### ISSUE THREAD

**Issue by sbkg0002** [immich-app/immich-charts#7]
Although Immich supports arm64 architecture, the reddis and postgresql images by Bitnami do not.

Any reason why the official images for these packages are not used? These are multi-arch.

I can create a PR to use them ofc.

**Comment by PixelJonas** [comment]
Hey @sbkg0002, there is no specific reason. Do you know if there are official Helm-Charts from them available as well? 

If you could draft a PR switching to another version that's fine by my as it would streamline our support of architectures with Immich

**Comment by jameswynn** [comment]
I recommend using these images for arm64: https://github.com/ZCube/bitnami-compat

**Comment by bo0tzz** [comment]
As of a few days ago, bitnami now supplies arm64 images themselves, so there's no need to switch to another chart or image. We might need to update the chart versions, though I haven't checked.

**Comment by jameswynn** [comment]
That's great news. Took them long enough 😂
