### ISSUE TITLE
Config file support

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich-charts#72]
Now that Immich supports YAML-formatted config files, support for those could be nicely integrated into the helm values

**Comment by hiteshnayak305** [comment]
Hello @bo0tzz ,

I would like to PR against this if not urgent.
:+1:

**Comment by hiteshnayak305** [comment]
Do we need both json and yaml? or json is sufficient.
As export settings feature give json file export.

**Comment by bo0tzz** [comment]
I would say let's do just yaml, since that will work nicely inside the helm values.yaml file
