### ISSUE TITLE
Use of schema validation for values

### ISSUE THREAD

**Issue by hiteshnayak305** [immich-app/immich-charts#77]
We can usevalues.schema.json file to validate values inputs instead of template functions. It will also populate good document in artifacthub.io

https://blog.artifacthub.io/blog/helm-values-schema-reference/

**Comment by bo0tzz** [comment]
The library chart we use has a schema in the latest version, but not in the version we use, and I'd rather not duplicate that work. However, so far I've avoided upgrading because it doesn't bring any other features or such that are needed, and it would be a somewhat annoying breaking change.

**Comment by bo0tzz** [comment]
(to note, I do think schema validation would be nice, but I don't think it's worth the effort right now)
