### ISSUE TITLE
Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by Bounteous17** [immich-app/immich-charts#78]
I'm trying to install the chart by using:
```bash
helm install immichtest -n immich ./charts/immich/ --set immich.persistence.library.existingClaim=nfs-immich --set redis.enabled=true --set postgresql.enabled=true --set global.postgresql.auth.postgresPassword=DBPassword123 --kube-context home-lab-cluster-0
```
But the logs for the POD `immich/immichtest-server-7494c4fd5d-c7wm8` are:
```
Error: getaddrinfo ENOTFOUND immichtest-redis-master
Error: getaddrinfo ENOTFOUND immichtest-postgresql
```

![image](https://github.com/immich-app/immich-charts/assets/16175933/421b1ffc-41dc-40ba-b4e4-ab1e3a27e166)

The Redis server did not received any request:
![image](https://github.com/immich-app/immich-charts/assets/16175933/63e6a2ad-6de2-4071-b1b8-ebc8fd4c20f0)

**Comment by bo0tzz** [comment]
Can you post the services that have been created by the chart?

**Comment by hiteshnayak305** [comment]
Check postgresql logs. if getting message similar to "database immich doesn't exist" try prividing existing claim to postgresql primary OR setup default storage class for volume provisioning.

**Comment by bo0tzz** [comment]
Closing as stale. Feel free to reopen this with more info if you're still having the issue.
