### ISSUE TITLE
Preview diffs in PRs

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich-charts#81]
When a PR to the chart is made, a github action should run `helm template` with the default values (and a placeholder for the library claim), diff the result against the main branch, and post this diff as a comment on the PR.

For bonus points, there should also be an option to request a diff with custom values by leaving a comment on the PR, such as

> 
> !diff
> ```values.yaml
> immich:
>   metrics:
>     enabled: true
> ```

**Comment by hiteshnayak305** [comment]
I can start on this.
