### ISSUE TITLE
0.6.0 not available in helm repository

### ISSUE THREAD

**Issue by paulfantom** [immich-app/immich-charts#85]
Seems that recent release of 0.6.0 version of this helm chart is not available in the repository listed in readme page.

When running the commands commands listed below, I get only 0.5.0 as the latest available version.

```bash
helm repo add immich https://immich-app.github.io/immich-charts
helm repo update
helm search repo immich
```

Seems to be related to failure in GitHub Action workflow related to release - https://github.com/immich-app/immich-charts/actions/runs/8613532110

**Comment by bo0tzz** [comment]
Thank you for catching this! Looks like it was an ephemeral failure in the github runner. I restarted the job and the chart should now be available.
