### ISSUE TITLE
Remove microservices container

### ISSUE THREAD

**Issue by bo0tzz** [immich-app/immich-charts#93]
The next release after creating this issue will remove the separate microservices container from the default deployment. We should match this in the chart and also remove the (currently hardcoded) entrypoint from server.

**Comment by Rahulsharma0810** [comment]
I got crashbackloop with 

image:
  tag: v1.106.1

microservices:
  enabled: true

I get the Crashbackloop 

```
immich/immich-server-67648469d9-9d6z6[immich-server]: /bin/sh: 0: cannot open ./start-server.sh: No such file
immich/immich-server-67648469d9-9d6z6[immich-server]: /bin/sh: 0: cannot open ./start-server.sh: No such file
immich/immich-server-67648469d9-9d6z6[immich-server]: /bin/sh: 0: cannot open ./start-server.sh: No such file
```

the effecting line in the chart is https://github.com/immich-app/immich-charts/blob/00a858d9a9d34958d86b0d94dc97b790eb558e97/charts/immich/templates/server.yaml#L7

Release notes remove it from compose file.
![image](https://github.com/immich-app/immich-charts/assets/9934859/7422fa95-de86-47d6-8a75-40ca2d854966)

**Comment by prometheanfire** [comment]
I assume this means the microservices container is undeployable now?
https://immich.app/docs/administration/jobs-workers/

**Comment by bo0tzz** [comment]
At the moment the chart doesn't have provisions for deploying distinct workers, see #94.

**Comment by prometheanfire** [comment]
thanks, subscribed
